version: "3.2"
services:
    hub:
        image: selenium/hub:3.13.0-argon
        ports:
            - "4444:4444"
        deploy:
            replicas: 1
        networks:
            selenium:
                aliases:
                    - hub
    chrome:
        image: selenium/node-chrome:3.13.0-argon
        deploy:
            replicas: 7
        networks:
            selenium:
                aliases:
                    - chrome
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        entrypoint: 'bash -c "SE_OPTS=\"-host $$HOSTNAME -port 5555 ${SE_OPTS}\" /opt/bin/entry_point.sh"'
    firefox:
        image: selenium/node-firefox:3.13.0-argon
        deploy:
            replicas: 7
        networks:
            selenium:
                aliases:
                    - firefox
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        entrypoint: 'bash -c "SE_OPTS=\"-host $$HOSTNAME -port 5555 ${SE_OPTS}\" /opt/bin/entry_point.sh"'
networks:
    selenium:
